USE [master]
GO

/****** Object:  Database [library]    Script Date: 11/11/2024 9:24:05 AM ******/
CREATE DATABASE [library]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'library', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\library.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'library_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\library_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [library].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [library] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [library] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [library] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [library] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [library] SET ARITHABORT OFF 
GO

ALTER DATABASE [library] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [library] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [library] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [library] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [library] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [library] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [library] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [library] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [library] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [library] SET  ENABLE_BROKER 
GO

ALTER DATABASE [library] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [library] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [library] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [library] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [library] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [library] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [library] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [library] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [library] SET  MULTI_USER 
GO

ALTER DATABASE [library] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [library] SET DB_CHAINING OFF 
GO

ALTER DATABASE [library] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [library] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [library] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [library] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [library] SET QUERY_STORE = OFF
GO

ALTER DATABASE [library] SET  READ_WRITE 
GO

