//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class books_catalog
    {
        public int book_id { get; set; }
        public string book_author { get; set; }
        public string book_title { get; set; }
        public string book_subject { get; set; }
        public string book_ISBN { get; set; }
    }
}
