//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public string user_name { get; set; }
        public int password { get; set; }
        public string name { get; set; }
        public Nullable<int> member_age { get; set; }
        public string member_phonenumber { get; set; }
    }
}
